feat: add action to update DVC SDKs to latest
DevCycleHQ/test-harness pull request #378
Opened 2024-03-08 19:54 UTC by jonathannorris

2024-03-08 19:54 UTC, jonathannorris commented
* **#378** <a href="https://app.graphite.dev/github/pr/DevCycleHQ/test-harness/378?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @jonathannorris and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-11 14:00 UTC, JamieSinn requested changes

2024-03-11 14:00 UTC, JamieSinn commented on .github/workflows/update-dvc-sdk.yml
> +          if [ "$IS_UPDATED" -gt "0" ]; then
Same as the other pr, don't compare numbers with string quotes

2024-03-11 15:36 UTC, JamieSinn commented on .github/workflows/update-dvc-sdk.yml
> +        run: |
```suggestion
        shell: bash
        run: |
```

2024-03-11 15:59 UTC, JamieSinn approved these changes

2024-03-11 17:51 UTC, merged